######################################################################
# Automatically generated by qmake (2.01a) Wed Jul 8 20:12:37 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += gotocelldialog.ui
SOURCES += main.cpp
