######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 7 15:07:45 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cpp
